"""esquema inicial sprint 1

Revision ID: 501d6a741051
Revises: 
Create Date: 2026-09-01 04:14:39.739236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501d6a741051'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sedes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialistas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA', 'TARJETA_IDENTIDAD', 'PASAPORTE', name='tipo_documento'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('acepto_tratamiento_datos', sa.Boolean(), nullable=False),
    sa.Column('fecha_aceptacion_tratamiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eps_id', sa.UUID(), nullable=True),
    sa.Column('estado_afiliacion', sa.Enum('PENDIENTE', 'ACTIVA', 'NO_ENCONTRADA', name='estado_afiliacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_numero_documento'), 'pacientes', ['numero_documento'], unique=True)
    op.create_table('codigos_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('canal', sa.Enum('WHATSAPP', name='canal_otp'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'USADO', 'EXPIRADO', 'INVALIDADO', name='estado_otp'), nullable=False),
    sa.Column('intentos_realizados', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_otp_paciente_id'), 'codigos_otp', ['paciente_id'], unique=False)
    op.create_table('disponibilidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('especialista_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', name='modalidad'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADO', name='estado_disponibilidad'), nullable=False),
    sa.ForeignKeyConstraint(['especialista_id'], ['especialistas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('especialista_id', 'sede_id', 'modalidad', 'fecha', 'hora', name='uq_disponibilidad_franja')
    )
    op.create_index(op.f('ix_disponibilidad_especialista_id'), 'disponibilidad', ['especialista_id'], unique=False)
    op.create_index(op.f('ix_disponibilidad_estado'), 'disponibilidad', ['estado'], unique=False)
    op.create_index(op.f('ix_disponibilidad_fecha'), 'disponibilidad', ['fecha'], unique=False)
    op.create_index(op.f('ix_disponibilidad_sede_id'), 'disponibilidad', ['sede_id'], unique=False)
    op.create_table('especialista_modalidades',
    sa.Column('especialista_id', sa.UUID(), nullable=False),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', name='modalidad'), nullable=False),
    sa.ForeignKeyConstraint(['especialista_id'], ['especialistas.id'], ),
    sa.PrimaryKeyConstraint('especialista_id', 'modalidad')
    )
    op.create_table('especialista_sedes',
    sa.Column('especialista_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['especialista_id'], ['especialistas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('especialista_id', 'sede_id')
    )
    op.create_table('citas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('disponibilidad_id', sa.UUID(), nullable=False),
    sa.Column('canal_recordatorio', sa.Enum('WHATSAPP', 'SMS', 'CORREO', 'LLAMADA', name='canal_contacto'), nullable=False),
    sa.Column('estado', sa.Enum('CONFIRMADA', name='estado_cita'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=20), nullable=True),
    sa.Column('canal_envio_comprobante', sa.Enum('WHATSAPP', 'SMS', 'CORREO', 'LLAMADA', name='canal_contacto'), nullable=True),
    sa.Column('comprobante_generado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disponibilidad_id'], ['disponibilidad.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disponibilidad_id'),
    sa.UniqueConstraint('numero_comprobante')
    )
    op.create_index(op.f('ix_citas_paciente_id'), 'citas', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citas_paciente_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_table('especialista_sedes')
    op.drop_table('especialista_modalidades')
    op.drop_index(op.f('ix_disponibilidad_sede_id'), table_name='disponibilidad')
    op.drop_index(op.f('ix_disponibilidad_fecha'), table_name='disponibilidad')
    op.drop_index(op.f('ix_disponibilidad_estado'), table_name='disponibilidad')
    op.drop_index(op.f('ix_disponibilidad_especialista_id'), table_name='disponibilidad')
    op.drop_table('disponibilidad')
    op.drop_index(op.f('ix_codigos_otp_paciente_id'), table_name='codigos_otp')
    op.drop_table('codigos_otp')
    op.drop_index(op.f('ix_pacientes_numero_documento'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('especialistas')
    op.drop_table('sedes')
    op.drop_table('especialidades')
    op.drop_table('eps')
    # ### end Alembic commands ###

    # NOTA (agregado a mano, no generado por autogenerate):
    # PostgreSQL no elimina los tipos ENUM al borrar las columnas/tablas
    # que los usan -- hay que hacerlo explícitamente o downgrade() deja
    # tipos huérfanos y un upgrade() posterior falla con
    # "type ... already exists". checkfirst=True evita error si alguno
    # ya no existiera.
    for enum_name in (
        "canal_contacto",
        "estado_cita",
        "modalidad",
        "estado_disponibilidad",
        "estado_otp",
        "canal_otp",
        "estado_afiliacion",
        "tipo_documento",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
